import './globals.css';
import Global from '@/components/Global';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='hide-scrollbar'>
      <body className={`antialiased`}>
        <Global />
        {children}
      </body>
    </html>
  );
}
